apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-develop-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-develop"
