apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: develop-db
  name: develop-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: develop-db
  type: ClusterIP
status:
  loadBalancer: {}
