apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: laravel-develop
  name: laravel-develop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: laravel-develop
  type: NodePort
status:
  loadBalancer: {}
